[project]
name = "deepeye"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "openai>=1.106.1",
    "pydantic>=2.11.7",
    "pytest>=8.4.2",
    "sqlalchemy>=2.0.43",
    "tenacity>=9.1.2",
    "tiktoken>=0.11.0",
]
